# This config file is used by ros2_control
controller_manager:
  ros__parameters:    

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    command_interfaces:
      - position
    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true


hand_controller:
  ros__parameters:
    joints:
      - joint_6

    command_interfaces:
      - position
    state_interfaces:
      - position


    open_loop_control: true
    allow_integration_in_goal_trajectories: true
